name: moodapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  image_picker: ^1.1.2
  fl_chart: ^0.35.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/home.png
    - assets/images/journals.png
    - assets/images/trends.png
    - assets/images/profile.png
    - assets/images/chatbot.png
    - assets/images/image_slider1.png
    - assets/images/splashcover.jpg
    - assets/images/logo.jpg